### ISSUE TITLE
Encryption key causes crash

### ISSUE THREAD

**Issue by tinoucas** [Boteium/bashbullet#3]
Hello,

Just installed from aur; using an encryption key (specified in "my_key="), I get the following output when receiving a notification:
```
tr: warning: an unescaped backslash at end of string is not portable
/usr/lib/node_modules/node-forge/js/aes.js:202
    var len = tmp.length();
                  ^

TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (/usr/lib/node_modules/node-forge/js/aes.js:202:19)
    at new forge.cipher.BlockCipher (/usr/lib/node_modules/node-forge/js/cipher.js:119:18)
    at Object.forge.cipher.createDecipher (/usr/lib/node_modules/node-forge/js/cipher.js:76:10)
    at Object.<anonymous> (/usr/share/bashbullet/dec.js:20:29)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
base64: invalid input
Invalid byte sequence in conversion input
```

**Comment by Boteium** [comment]
I'm not sure what's going on.
Did you generate "my_key" from keygen.js ? Also make sure nodejs-atob, nodejs-btoa, nodejs-node-forge are all installed.

**Comment by tinoucas** [comment]
Ok, I didn't read the config_example correctly, my bad.
Now that I've generated it with keygen.js, I don't get a backtrace anymore, just this:
```
tr: warning: an unescaped backslash at end of string is not portable
base64: invalid input
```
and the generated my_key doesn't seem to have illegal base64 characters (only alphabetic, slashes, plus sign and an equal sign at the end).

**Comment by Boteium** [comment]
Just ignore the warning. Is notification mirroring working now ?

**Comment by tinoucas** [comment]
No, nothing else happens.

**Comment by tinoucas** [comment]
Pushing to phone works, not sure if it's relevant.

**Comment by Boteium** [comment]
So, pushes (which doesn't involve encryption) works. But notification mirroring doesn't work. Nothing popped up as if there isn't any notification at all. Despite the fact that it's not working, it doesn't crash.

**Comment by tinoucas** [comment]
I found my problem: I'm missing a notification center, notify-send is called correctly.
Thanks :)
